server {
    listen 8080;
    
    # Вказуємо шлях до MIME-типів (стандарт для alpine-образів)
    include /etc/nginx/mime.types;
    
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}